"""Database connection and session management."""
import contextvars
import os
import re
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker, AsyncConnection
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy import event, text

_UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", re.I)

# Priority: DATABASE_URL env var → PostgreSQL default (configured in apps/api/.env)
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+asyncpg://tiza_user:tiza_password@localhost:5432/tiza_dev",
)

_is_sqlite = DATABASE_URL.startswith("sqlite")

engine = create_async_engine(DATABASE_URL, echo=False)


if _is_sqlite:

    @event.listens_for(engine.sync_engine, "connect")
    def set_sqlite_pragma(dbapi_connection, connection_record):
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()


async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

# ─── Schema-per-Tenant: Context variable for current tenant ──────────
# Set by TenantMiddleware and read by get_db() to configure search_path.
current_tenant_id: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "current_tenant_id", default=None
)


def _is_postgres() -> bool:
    """Check if the current engine is PostgreSQL (not SQLite)."""
    return not engine.url.get_backend_name().startswith("sqlite")


async def set_tenant_search_path(session: AsyncSession, tenant_id: str | None):
    """Set the PostgreSQL search_path for tenant data isolation.

    When tenant_id is set, queries first hit tenant_{uuid} schema,
    then fall back to public. Otherwise, only public is visible.

    ponytail: SQLite has no schemas — this is a no-op in tests/local dev
    with SQLite. Tenant isolation is handled via the search_path in PG.
    """
    if not _is_postgres():
        return  # SQLite has no schemas — tenant isolation via app-level filters
    if tenant_id:
        if not _UUID_RE.match(tenant_id):
            raise ValueError(f"Invalid tenant_id format: {tenant_id}")
        # SECURITY: tenant_id is a UUID (generated by generate_uuid), not
        # user-supplied, so safe for string interpolation in SET search_path.
        # NOTE: The schema name is double-quoted because it contains hyphens
        # (e.g., tenant_2777e7b7-a8ea-...) and PostgreSQL requires quoted
        # identifiers for names with special characters.
        await session.execute(text(f'SET search_path TO "tenant_{tenant_id}", public'))
    else:
        await session.execute(text("SET search_path TO public"))


async def create_tenant_schema(tenant_id: str):
    """Create a new tenant schema with all required tables.

    Called when a new tenant is registered. Creates the schema and its
    tables for data isolation. The schema is named ``tenant_{uuid}``.

    SECURITY: tenant_id is a server-generated UUID, safe for string
    interpolation in DDL statements.

    ponytail: SQLite has no schemas — this is a no-op for tests.
    """
    if not _is_postgres():
        return  # SQLite: all tables in a single file, no schema isolation
    if tenant_id and not _UUID_RE.match(tenant_id):
        raise ValueError(f"Invalid tenant_id format: {tenant_id}")
    # Both the schema name and index names must be double-quoted because
    # they contain UUID-derived hyphens (e.g., tenant_2777e7b7-a8ea-...).
    schema = f'"tenant_{tenant_id}"'
    idx_prefix = f'"ix_{tenant_id}'  # closing quote added per index
    async with engine.begin() as conn:
        await conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema}"))

        await conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {schema}.evaluations (
                id VARCHAR PRIMARY KEY,
                title VARCHAR NOT NULL,
                subject VARCHAR NOT NULL,
                grade VARCHAR NOT NULL,
                rubric JSON NOT NULL DEFAULT '[]'::json,
                pdf_url VARCHAR,
                status VARCHAR DEFAULT 'pending',
                deleted_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            )
        """))
        await conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {schema}.courses (
                id VARCHAR PRIMARY KEY,
                name VARCHAR NOT NULL,
                grade VARCHAR NOT NULL,
                subject VARCHAR NOT NULL,
                teacher_id VARCHAR NOT NULL,
                deleted_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            )
        """))
        await conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {schema}.results (
                id VARCHAR PRIMARY KEY,
                evaluation_id VARCHAR NOT NULL REFERENCES {schema}.evaluations(id) ON DELETE CASCADE,
                student_code VARCHAR NOT NULL,
                answers JSON DEFAULT '[]'::json,
                confidence FLOAT DEFAULT 0.0,
                requires_review BOOLEAN DEFAULT FALSE,
                final_grade FLOAT,
                status VARCHAR DEFAULT 'pending',
                feedback_pdf_url VARCHAR,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            )
        """))
        await conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {schema}.students (
                id VARCHAR PRIMARY KEY,
                course_id VARCHAR NOT NULL REFERENCES {schema}.courses(id) ON DELETE CASCADE,
                full_name VARCHAR NOT NULL,
                student_code VARCHAR NOT NULL,
                rut VARCHAR,
                email VARCHAR,
                deleted_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            )
        """))

        # Create indices for performance
        # NOTE: Index names are double-quoted because they contain hyphens
        # from the UUID in the tenant_id (e.g., ix_2777e7b7-a8ea-..._status).
        await conn.execute(text(f"""
            CREATE INDEX IF NOT EXISTS "{idx_prefix}_evaluations_status"
            ON {schema}.evaluations (status)
        """))
        await conn.execute(text(f"""
            CREATE INDEX IF NOT EXISTS "{idx_prefix}_courses_teacher_id"
            ON {schema}.courses (teacher_id)
        """))
        await conn.execute(text(f"""
            CREATE INDEX IF NOT EXISTS "{idx_prefix}_results_evaluation_id"
            ON {schema}.results (evaluation_id)
        """))
        await conn.execute(text(f"""
            CREATE INDEX IF NOT EXISTS "{idx_prefix}_students_course_id"
            ON {schema}.students (course_id)
        """))


class Base(DeclarativeBase):
    pass


async def get_db():
    """Yield a session. Endpoints MUST commit explicitly before returning
    if they modified data. This generator rolls back on exception.

    Sets the PostgreSQL search_path for schema-per-tenant isolation
    based on the current_tenant_id context variable (set by
    TenantMiddleware).
    """
    async with async_session() as session:
        try:
            tid = current_tenant_id.get()
            await set_tenant_search_path(session, tid)
            yield session
            await session.commit()
        except BaseException:
            await session.rollback()
            raise
